Logging model files to ./chkp/12-31-2022_14:26:06
TRAINING MODEL: regressor
Training on CPU
************* EPOCH: 1 *************
> /Users/stephennelson/Projects/Learning-Frustum-Proposals/models/pointnet.py(163)forward()
-> x = self.conv_layers[0](x)
(Pdb)

(Pdb) x.shape
torch.Size([1, 3, 262])

(Pdb) x = self.conv_layers[0](x)

(Pdb) x.shape
torch.Size([1, 64, 262])

(Pdb) continue
  0%|                                                                                                                               | 0/1 [03:11<?, ?it/s]
Traceback (most recent call last):
  File "train_frustum_neonet.py", line 101, in <module>
    main(args)
  File "train_frustum_neonet.py", line 89, in main
    trainer.fit()
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/trainers/base_trainer.py", line 345, in fit
    y_hat = self._batch_prediction(inputs).to(self.device)
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/trainers/learned_frustum_trainer.py", line 54, in _batch_prediction
    y_hat = self.model(
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/models/frustum_neonet.py", line 30, in forward
    h = self.encoder(points)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/stephennelson/Projects/Learning-Frustum-Proposals/models/pointnet.py", line 163, in forward
    x = self.conv_layers[0](x)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 298, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/anaconda3/envs/thesis/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 294, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 1], expected input[1, 64, 262] to have 3 channels, but got 64 channels instead